### ISSUE TITLE
Feature Request: get bytecode from stdin?

### ISSUE THREAD

**Issue by TheKidThatCodes** [societall/UnluauNET#2]
would this be possible?
maybe a `--stdin` flag or something?
im making a python webserver decompiler thingy so i can decompile in script ware and using it the way it is i would have to create a file every time it needs to decompile.

**Comment by TheKidThatCodes** [comment]
i have downloaded a zip of the repo and added to unluau.cli
wating for this to be implemented

**Comment by societall** [comment]
Sorry for the late response, I have not been so active on this account lately.

Now, if you want to provide bytecode through stdin, just don't pass an input file. Unluau will immediately read from the command line.
